
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The system is: Windows - 10.0.22631 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:2 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.13.19+0d9f5a35a for .NET Framework
      Build started 08-04-2025 01:15:12 AM.
      
      Project "E:\\programming\\NetworkingLAB\\CLAY\\clay-main\\examples\\cairo-pdf-rendering\\CMakeFiles\\3.27.4\\CompilerIdC\\CompilerIdC.vcxproj" on node 1 (default targets).
      PrepareForBuild:
        Creating directory "Debug\\".
        Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
        Creating directory "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Creating "Debug\\CompilerIdC.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
        Touching "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> E:\\programming\\NetworkingLAB\\CLAY\\clay-main\\examples\\cairo-pdf-rendering\\CMakeFiles\\3.27.4\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.43.34808\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Deleting file "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Touching "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Done Building Project "E:\\programming\\NetworkingLAB\\CLAY\\clay-main\\examples\\cairo-pdf-rendering\\CMakeFiles\\3.27.4\\CompilerIdC\\CompilerIdC.vcxproj" (default targets).
      
      Build succeeded.
          0 Warning(s)
          0 Error(s)
      
      Time Elapsed 00:00:00.66
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        E:/programming/NetworkingLAB/CLAY/clay-main/examples/cairo-pdf-rendering/CMakeFiles/3.27.4/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:2 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "E:/programming/NetworkingLAB/CLAY/clay-main/examples/cairo-pdf-rendering/CMakeFiles/CMakeScratch/TryCompile-0lye11"
      binary: "E:/programming/NetworkingLAB/CLAY/clay-main/examples/cairo-pdf-rendering/CMakeFiles/CMakeScratch/TryCompile-0lye11"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS"
      CMAKE_C_FLAGS_DEBUG: "/Ob0 /Od /RTC1"
      CMAKE_EXE_LINKER_FLAGS: "/machine:x64"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'E:/programming/NetworkingLAB/CLAY/clay-main/examples/cairo-pdf-rendering/CMakeFiles/CMakeScratch/TryCompile-0lye11'
        
        Run Build Command(s): "C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_be07f.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
        MSBuild version 17.13.19+0d9f5a35a for .NET Framework
        Build started 08-04-2025 01:15:13 AM.
        
        Project "E:\\programming\\NetworkingLAB\\CLAY\\clay-main\\examples\\cairo-pdf-rendering\\CMakeFiles\\CMakeScratch\\TryCompile-0lye11\\cmTC_be07f.vcxproj" on node 1 (default targets).
        PrepareForBuild:
          Creating directory "cmTC_be07f.dir\\Debug\\".
          Structured output is enabled. The formatting of compiler diagnostics will reflect the error hierarchy. See https://aka.ms/cpp/structured-output for more details.
          Creating directory "E:\\programming\\NetworkingLAB\\CLAY\\clay-main\\examples\\cairo-pdf-rendering\\CMakeFiles\\CMakeScratch\\TryCompile-0lye11\\Debug\\".
          Creating directory "cmTC_be07f.dir\\Debug\\cmTC_be07f.tlog\\".
        InitializeBuildStatus:
          Creating "cmTC_be07f.dir\\Debug\\cmTC_be07f.tlog\\unsuccessfulbuild" because "AlwaysCreate" was specified.
          Touching "cmTC_be07f.dir\\Debug\\cmTC_be07f.tlog\\unsuccessfulbuild".
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX64\\x64\\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_be07f.dir\\Debug\\\\" /Fd"cmTC_be07f.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          Microsoft (R) C/C++ Optimizing Compiler Version 19.43.34809 for x64
          Copyright (C) Microsoft Corporation.  All rights reserved.
          cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_be07f.dir\\Debug\\\\" /Fd"cmTC_be07f.dir\\Debug\\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.27\\Modules\\CMakeCCompilerABI.c"
          CMakeCCompilerABI.c
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.43.34808\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"E:\\programming\\NetworkingLAB\\CLAY\\clay-main\\examples\\cairo-pdf-rendering\\CMakeFiles\\CMakeScratch\\TryCompile-0lye11\\Debug\\cmTC_be07f.exe" /INCREMENTAL /ILK:"cmTC_be07f.dir\\Debug\\cmTC_be07f.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:/programming/NetworkingLAB/CLAY/clay-main/examples/cairo-pdf-rendering/CMakeFiles/CMakeScratch/TryCompile-0lye11/Debug/cmTC_be07f.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:/programming/NetworkingLAB/CLAY/clay-main/examples/cairo-pdf-rendering/CMakeFiles/CMakeScratch/TryCompile-0lye11/Debug/cmTC_be07f.lib" /MACHINE:X64  /machine:x64 cmTC_be07f.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_be07f.vcxproj -> E:\\programming\\NetworkingLAB\\CLAY\\clay-main\\examples\\cairo-pdf-rendering\\CMakeFiles\\CMakeScratch\\TryCompile-0lye11\\Debug\\cmTC_be07f.exe
        FinalizeBuildStatus:
          Deleting file "cmTC_be07f.dir\\Debug\\cmTC_be07f.tlog\\unsuccessfulbuild".
          Touching "cmTC_be07f.dir\\Debug\\cmTC_be07f.tlog\\cmTC_be07f.lastbuildstate".
        Done Building Project "E:\\programming\\NetworkingLAB\\CLAY\\clay-main\\examples\\cairo-pdf-rendering\\CMakeFiles\\CMakeScratch\\TryCompile-0lye11\\cmTC_be07f.vcxproj" (default targets).
        
        Build succeeded.
            0 Warning(s)
            0 Error(s)
        
        Time Elapsed 00:00:00.52
        
      exitCode: 0
...
